# Generated by Django 5.2.11 on 2026-02-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('product', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10)),
                ('delivery_date', models.DateField(db_index=True)),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente de procesar'), ('entregado', 'Porducto entregado'), ('cancelado', 'Producto cancelado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
