# Generated by Django 5.2.11 on 2026-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_backend_pasteleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
