# Generated by Django 5.2.11 on 2026-02-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_backend_pasteleria', '0002_alter_orders_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
