# Generated by Django 5.2.11 on 2026-02-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_backend_pasteleria', '0003_alter_orders_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
